### ISSUE TITLE
Crash on Windows 8.1 machines that only have XInput 1.4

### ISSUE THREAD

**Issue by hymerman** [speps/XInputDotNet#13]
I've been happily using XInputDotNet in a Unity project running on a number of different machines, but the other day I ran it on a relatively clean Windows 8.1 machine and it crashed, which after lots of digging turned out to be because it's expecting XInput 1.3 to be installed, but the default that comes with Windows 8.1 is XInput 1.4 (xinput1_3.dll was missing and instead xinput1_4.dll was present).

It looks like XInputDotNet is explicitly built against XInput 1.3 - I've not tried to build it myself since I'm short on time but I thought I'd report this to find out if it's a known issue. I see the readme mentions the June 2010 DirectX SDK - does that mean it's a requirement for any project using XInputDotNet?

More info on XInput versions here:
https://msdn.microsoft.com/en-us/library/windows/desktop/hh405051(v=vs.85).aspx

**Comment by speps** [comment]
Yeah it's a known issue unfortunately. As I don't have a Windows 8 machine at home for now, I can't really work on this but I would happily accept a pull request. Basically, what it needs is a loop where I do LoadLibrary and find the first one available. Right now it only tries to load xinput1_3.dll. Because of that the DirectX SDK June 2010 runtime is a requirement.
