### ISSUE TITLE
DllNotFoundException for XInputInterface.dll

### ISSUE THREAD

**Issue by pbhogan** [speps/XInputDotNet#4]
I can't seem to get this to work at all. The example Unity project throws DllNotFoundException for XInputInterface. XInputDemo.exe and XInputReporter.exe don't work either. XInputDemo crashes. XInputReporter loads but doesn't do anything.

I'm using Windows 7 Home Premium SP 1 on a 64 bit system and Unity 4.3.4

Any idea what's going on?

**Comment by SDanton** [comment]
Seems like I've hit this issue. Wondering if you can help. Big thanks in advance!

I'm running Windows 8.1 - 64bit on Unity 4.6.1.

When running in the editor I get the error noted earlier in the discussion...
```
DllNotFoundException: XInputInterface
XInputDotNetPure.GamePad.GetState (PlayerIndex playerIndex, GamePadDeadZone deadZone)
XboxCtrlrInput.XCI.XInputUpdateAllStates () (at Assets/Code/XboxCtrlrInput.cs:1193)
XboxCtrlrInput.XCI.GetAxis (XboxAxis axis) (at Assets/Code/XboxCtrlrInput.cs:623)
HeroController.handleInput () (at Assets/Code/HeroController.cs:234)
HeroController.Update () (at Assets/Code/HeroController.cs:452)
```

When running the Example Project I get the same error...

```
DllNotFoundException: XInputInterface
XInputDotNetPure.GamePad.GetState (PlayerIndex playerIndex, GamePadDeadZone deadZone)
XboxCtrlrInput.XCI.XInputUpdateAllStates () (at Assets/XboxCtrlrInputPackage/XboxCtrlrInput.cs:1193)
XboxCtrlrInput.XCI.GetNumPluggedCtrlrs () (at Assets/XboxCtrlrInputPackage/XboxCtrlrInput.cs:771)
MovePlayer.Start () (at Assets/XboxCtrlrInputPackage/Test Level Scripts/MovePlayer.cs:57)
```

I've tried running my project outside of the editor both as a 32 and 64 bit version and hit the same issue. In my particular case the game loads, but then immediately hangs.

When I run the Example Project I see all four "players" drop into the world, coloured red, green, blue and yellow, with each of them shooting coloured balls in all four directions. I cannot move any of them, the game appears to be locked in this state.

FWIW, I really like what you've done with this addon. I can say that because I have everything running perfectly on a Mac :).

Let me know if I can help in any way. Cheers!

**Comment by SDanton** [comment]
I should note that I was able to get things running on a Windows 7 32bit machine. But the above issue still remains on my Windows 8.1 64bit machine. Again thanks for any insight here.

**Comment by speps** [comment]
Did you try what @pbhogan said in his latest message?

> It was missing xinput1_3.dll. I reinstalled DirectX and now everything works. Might be worth putting a note in the README just saying as a sanity check install the latest version of DirectX.

Apart from this, I've heard that it works on Windows 8 (x64 or not), but as mentioned in this quote, it still requires the DirectX June 2010 Runtime (or just the xinput1_3.dll next to the XInputInterface.dll, i.e. in the Project folder (not the Assets folder)).

**Comment by SDanton** [comment]
That seemed to work. Thanks for the reminder... should have tried that earlier, sorry :).
